name: ReplicateBug

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:

  commit:
    runs-on: ubuntu-latest


    steps:

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Restore packages
        run: flutter pub get

      - name: Run it
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          profile: Nexus 6
          script: flutter run lib/main.dart & sleep 120; kill -SIGUSR1 $! ; sleep 10 ; kill $1