name: ReplicateBug

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:

  commit:
    runs-on: ubuntu-latest


    steps:

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Restore packages
        run: flutter pub get

      - name: Doctor
        run: flutter doctor -v

      - name: Run it
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          profile: Nexus 6
          script: flutter run lib/main.dart --pid-file pid & sleep 1000; for run in $(seq 10); do echo "Trying to hot restart"; (kill -USR2 $(cat pid) || break) && sleep 60; done; kill $!